### ISSUE TITLE
Problem with csrf token  on firefox

### ISSUE THREAD

**Issue by donMichaelL** [pasupulaphani/angular-csrf-cross-domain#4]
i use django (with django-rest-framework) and angularJS.
When i am trying to post some data in an angular form on Chrome everything works fine. (with or without including your dependency 
angular.module('buildingApp',['csrf-cross-domain']);

In firefox i got an error XHR 403 Forbidden.
Have you any idea  
i use  angularjs/1.5.0-rc.0
       angular cookies 1.2.29

**Comment by pasupulaphani** [comment]
Sorry I haven't experienced it. Need more info on how ur app/server is set-up.

It could be naming convention for csrf tokens. Every framework has different default naming for tokens. Please see the README.md for more info.

**Comment by pasupulaphani** [comment]
Please feel free to open with more info.
