### ISSUE TITLE
When this package usefull

### ISSUE THREAD

**Issue by knvpk** [pasupulaphani/angular-csrf-cross-domain#5]
Hi , Im actually working on the site with app, i have created a laravel backend with domain `api.something.com`, and my website is on the `www.something.com` and an app for this also. For xsrf anit attack laravel has a way as documented [here](https://laravel.com/docs/5.2/routing#csrf-x-xsrf-token)   ... So im trying o get the cookie from `api.something.com` and setting the XSRF header while sending post request to `api.something.com` but its not working because cookies of `api.something.com` can be accessed by only the same domain so its not working, then really im worry that what is the use of this package. I mean which header to be set from where.

**Comment by pasupulaphani** [comment]
Hi Pavan, I'm still confused what your question is?

**Comment by knvpk** [comment]
Hi @pasupulaphani , please give a use case of this package.
