### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by rscottfree** [pasupulaphani/angular-csrf-cross-domain#6]
Any plans to put this up on NPM?

**Comment by pasupulaphani** [comment]
I can put it on npm if it helps you. Usually "bower" is preferred over npm for packages related to html, css. js...

**Comment by rscottfree** [comment]
@pasupulaphani That's what I thought too :) But then lodash didn't want to put their latest version on Bower, recommending we just use NPM for everything. And NPM is actually working fine -- I just pull angular-csrf-cross-domain directly from Github.
